const mongoose = require("mongoose");
const Car = require("./models/Car");
require("dotenv").config();

const dummyCars = [
  {
    name: "Toyota",
    model: "Corolla",
    year: 2020,
    mileage: 45000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    engine: "1.8L 4-Cylinder",
    color: "White",
    ownershipHistory: "Single owner, well maintained",
    verifiedSeller: true,
    status: "Published",
    price: 1850000,
    location: "Nairobi",
    images: ["https://via.placeholder.com/400x300?text=Toyota+Corolla"],
  },
  {
    name: "Honda",
    model: "Civic",
    year: 2019,
    mileage: 52000,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Sedan",
    engine: "1.5L Turbo",
    color: "Black",
    ownershipHistory: "Two owners, service records available",
    verifiedSeller: false,
    status: "Published",
    price: 1650000,
    location: "Kisumu",
    images: ["https://via.placeholder.com/400x300?text=Honda+Civic"],
  },
  {
    name: "Nissan",
    model: "Qashqai",
    year: 2021,
    mileage: 28000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.0L 4-Cylinder",
    color: "Silver",
    ownershipHistory: "Single owner, imported",
    verifiedSeller: true,
    status: "Published",
    price: 2450000,
    location: "Eldoret",
    images: ["https://via.placeholder.com/400x300?text=Nissan+Qashqai"],
  },
  {
    name: "Mazda",
    model: "CX-5",
    year: 2018,
    mileage: 65000,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.2L Turbo Diesel",
    color: "Blue",
    ownershipHistory: "Two owners, accident free",
    verifiedSeller: false,
    status: "Published",
    price: 2100000,
    location: "Nakuru",
    images: ["https://via.placeholder.com/400x300?text=Mazda+CX-5"],
  },
  {
    name: "Subaru",
    model: "Forester",
    year: 2022,
    mileage: 15000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.5L Boxer",
    color: "Green",
    ownershipHistory: "Single owner, brand new condition",
    verifiedSeller: true,
    status: "Published",
    price: 3200000,
    location: "Nairobi",
    images: ["https://via.placeholder.com/400x300?text=Subaru+Forester"],
  },
  {
    name: "Mitsubishi",
    model: "Outlander",
    year: 2019,
    mileage: 48000,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.0L Hybrid",
    color: "Red",
    ownershipHistory: "Single owner, low mileage",
    verifiedSeller: true,
    status: "Published",
    price: 2750000,
    location: "Kisumu",
    images: ["https://via.placeholder.com/400x300?text=Mitsubishi+Outlander"],
  },
  {
    name: "Kia",
    model: "Sportage",
    year: 2020,
    mileage: 35000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.0L 4-Cylinder",
    color: "White",
    ownershipHistory: "Single owner, warranty remaining",
    verifiedSeller: false,
    status: "Published",
    price: 1950000,
    location: "Eldoret",
    images: ["https://via.placeholder.com/400x300?text=Kia+Sportage"],
  },
  {
    name: "Hyundai",
    model: "Tucson",
    year: 2017,
    mileage: 78000,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "SUV",
    engine: "1.7L CRDi",
    color: "Gray",
    ownershipHistory: "Three owners, well maintained",
    verifiedSeller: false,
    status: "Published",
    price: 1450000,
    location: "Nakuru",
    images: ["https://via.placeholder.com/400x300?text=Hyundai+Tucson"],
  },
  {
    name: "Ford",
    model: "Ranger",
    year: 2018,
    mileage: 95000,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Pickup",
    engine: "3.2L TDCi",
    color: "Blue",
    ownershipHistory: "Two owners, work truck",
    verifiedSeller: true,
    status: "Published",
    price: 1850000,
    location: "Nairobi",
    images: ["https://via.placeholder.com/400x300?text=Ford+Ranger"],
  },
  {
    name: "Chevrolet",
    model: "Spark",
    year: 2021,
    mileage: 22000,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    engine: "1.0L 3-Cylinder",
    color: "Yellow",
    ownershipHistory: "Single owner, city car",
    verifiedSeller: false,
    status: "Published",
    price: 850000,
    location: "Kisumu",
    images: ["https://via.placeholder.com/400x300?text=Chevrolet+Spark"],
  },
  {
    name: "Toyota",
    model: "Hilux",
    year: 2019,
    mileage: 60000,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Pickup",
    engine: "2.4L Turbo Diesel",
    color: "White",
    ownershipHistory: "Single owner, off-road ready",
    verifiedSeller: true,
    status: "Published",
    price: 2650000,
    location: "Eldoret",
    images: ["https://via.placeholder.com/400x300?text=Toyota+Hilux"],
  },
  {
    name: "Honda",
    model: "CR-V",
    year: 2020,
    mileage: 38000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.0L 4-Cylinder",
    color: "Black",
    ownershipHistory: "Single owner, family vehicle",
    verifiedSeller: true,
    status: "Published",
    price: 2850000,
    location: "Nakuru",
    images: ["https://via.placeholder.com/400x300?text=Honda+CR-V"],
  },
  {
    name: "Nissan",
    model: "Patrol",
    year: 2016,
    mileage: 120000,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "3.0L V6 Turbo Diesel",
    color: "Silver",
    ownershipHistory: "Three owners, heavy duty",
    verifiedSeller: false,
    status: "Published",
    price: 3200000,
    location: "Nairobi",
    images: ["https://via.placeholder.com/400x300?text=Nissan+Patrol"],
  },
  {
    name: "Mazda",
    model: "Demio",
    year: 2022,
    mileage: 8000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    engine: "1.5L Skyactiv-G",
    color: "Red",
    ownershipHistory: "Single owner, almost new",
    verifiedSeller: true,
    status: "Published",
    price: 1250000,
    location: "Kisumu",
    images: ["https://via.placeholder.com/400x300?text=Mazda+Demio"],
  },
  {
    name: "Subaru",
    model: "Impreza",
    year: 2018,
    mileage: 55000,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Sedan",
    engine: "2.0L Boxer",
    color: "Blue",
    ownershipHistory: "Two owners, sporty",
    verifiedSeller: false,
    status: "Published",
    price: 1650000,
    location: "Eldoret",
    images: ["https://via.placeholder.com/400x300?text=Subaru+Impreza"],
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || "mongodb://localhost:27017/simba-motors"
    );

    // Check if cars already exist
    const existingCars = await Car.countDocuments();
    if (existingCars > 0) {
      console.log(`Database already has ${existingCars} cars. Skipping seeding to preserve existing data.`);
      process.exit(0);
    }

    // Insert dummy cars only if database is empty
    await Car.insertMany(dummyCars);

    console.log("Database seeded successfully with dummy car data!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
